# Python is required for the deploy script
language: python
python:
- '3.5'

# The Sass part is the actual build
install:
- rvm install 2.4.1
# - gem install sass
- pip install -r .update/requirements.txt
script:
- echo "Nothing to do, we're not actually compiling sass"
deploy:
- on:
    branch: master
  provider: script
  script: python .update/updateSubreddit.py anime
  skip_cleanup: true
- on:
    branch: dev
  provider: script
  script: python .update/updateSubreddit.py animestaging
  skip_cleanup: true
