# Python is required for the deploy script
language: python
python:
- '3.5'

# The Sass part is the actual build
install:
- rvm install 2.4.1
- gem install sass
script:
- sass main.scss style.css

# If we got a commit to master, sync it with Reddit
after_success:
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    REV_EDIT_MSG=$(git log -1 --pretty=%B | tr -d '\n')
    REV_EDIT_MSG=${REV_EDIT_MSG:-"<no commit message>"}
    export REV_EDIT_MSG
    cd .update;
    pip install -r requirements.txt;
    python updateSubreddit.py;
  fi
