language: python
python:
- '3.5'
install: pip install -r update/requirements.txt
script: cd update && python updateSubreddit.py
before_install:
- openssl aes-256-cbc -K $encrypted_3399cde0837c_key -iv $encrypted_3399cde0837c_iv
  -in oauth.ini.enc -out update/oauth.ini -d
- openssl aes-256-cbc -K $encrypted_29d61053c17a_key -iv $encrypted_29d61053c17a_iv
  -in oauth.ini.enc -out oauth.ini -d
