language: python
python:
- '3.5'
before_install:
- gem install sass
install:
- echo test
script:
- sass main.scss style.css
after_success:
- if [ "$TRAVIS_BRANCH" = "nothing" ]; then
    cd update
    pip install -r update/requirements.txt
    openssl aes-256-cbc -K $encrypted_4f59f0e49779_key -iv $encrypted_4f59f0e49779_iv -in config.json.enc -out config.json -d
    python updateSubreddit.py
  fi
