# Python is required for the deploy script
language: python
python:
- '3.5'

# The Sass part is the actual build
install:
- gem install sass
script:
- sass main.scss style.css

# If we got a commit to master, sync it with Reddit
after_success:
- if [ "$TRAVIS_BRANCH" = "master" ]; then
    cd .update;
    pip install -r requirements.txt;
    python updateSubreddit.py;
  fi
