language: python
python:
- '3.6'

install:
- pip install -r utils/requirements.txt

script:
- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    if [ "$TRAVIS_BRANCH" = "master" ]; then
      python utils/build.py --subreddit_name anime;
    else
      python utils/build.py --subreddit_name animestaging;
    fi
  else
    python utils/validate.py;
  fi

deploy:
- on:
    all_branches: true
  provider: script
  script: python utils/update.py
  skip_cleanup: true
