# Python is required for the deploy script
language: python
python:
- '3.5'

# The Sass part is the actual build
install:
- rvm install 2.4.1
# - gem install sass
- pip install -r .update/requirements.txt
# script:
# - sass main.scss style.css
deploy:
  provider: script
  script: python .update/updateSubreddit.py
  skip_cleanup: true
  on:
    branch: master
